<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="acer" ignored="2" name="restAssuredTests(failed)" tests="4" failures="3" timestamp="16 Apr 2020 09:56:28 GMT" time="14.012" errors="0">
  <testcase name="CheckResponseBody" time="0.01" classname="com.restassured.testcases.TC005_DELETE_Employee">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;true&amp;gt; but was:&amp;lt;false&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<true> but was:<false>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:147)
at junit.framework.Assert.assertEquals(Assert.java:153)
at com.restassured.testcases.TC005_DELETE_Employee.CheckResponseBody(TC005_DELETE_Employee.java:48)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- CheckResponseBody -->
  <testcase name="CheckResponseTime" time="0.003" classname="com.restassured.testcases.TC002_GET_SingleEmployee"/>
  <testcase name="CheckStatusCode" time="0.003" classname="com.restassured.testcases.TC002_GET_SingleEmployee">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;200&amp;gt; but was:&amp;lt;400&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<400>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:199)
at junit.framework.Assert.assertEquals(Assert.java:205)
at com.restassured.testcases.TC002_GET_SingleEmployee.CheckStatusCode(TC002_GET_SingleEmployee.java:50)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- CheckStatusCode -->
  <testcase name="CheckResponseBody" time="0.003" classname="com.restassured.testcases.TC002_GET_SingleEmployee">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;false&amp;gt; but was:&amp;lt;true&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<false> but was:<true>
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.failNotEquals(Assert.java:287)
at junit.framework.Assert.assertEquals(Assert.java:67)
at junit.framework.Assert.assertEquals(Assert.java:147)
at junit.framework.Assert.assertEquals(Assert.java:153)
at com.restassured.testcases.TC002_GET_SingleEmployee.CheckResponseBody(TC002_GET_SingleEmployee.java:40)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- CheckResponseBody -->
  <testcase name="CheckStatusCode" time="0.0" classname="com.restassured.testcases.TC005_DELETE_Employee">
    <ignored/>
  </testcase> <!-- CheckStatusCode -->
  <testcase name="CheckResponseTime" time="0.0" classname="com.restassured.testcases.TC005_DELETE_Employee">
    <ignored/>
  </testcase> <!-- CheckResponseTime -->
</testsuite> <!-- restAssuredTests(failed) -->
